### PR TITLE
Optimising!

### PR DESCRIPTION
**Pull request by Jezza**
Fixed localisation.
Made it MUCH more dynamic for future use.

### CODE REVIEW

**Comment by gellegbs** [comment]
Thank you Jezza <3

**Comment by Jezza** [comment]
:)
If you need a hand to work out what does what, I can spare some time.

**Comment by gellegbs** [comment]
ok I start my classes today going to go early for a workout I might have
time tomorrow let me know your schedule.

**Comment by Jezza** [comment]
Whenever you're free, just message me.

**Pull request merged**
